---
title: "findings_table"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r table2, echo=FALSE, message=FALSE, warnings=FALSE, results='asis'}
##Corresponds with lauren_blog1

tabl <- "
| Education Mandate        | Health Outcome  |  Interesting Insight |
|---------------|:-------------:|
| Sexual decision making and self-discipline | % students intoxicated   |  Suggests that education on sexual decision making may not be effective, since those states where most students were intoxicated during their last sexual encounter do mandate this type of education. |
| Sex Ed Marriage | % students with one or more partners  | The three states in which the most students have had four or more sexual partners also mandate sex ed that emphasises waiting for marriage to have sex. |"

cat(tabl) # output the table in a format good for HTML/PDF/docx conversion
```
```{r table2, echo=FALSE, message=FALSE, warnings=FALSE, results='asis'}
##Corresponds with lauren_blog1

tabl <- "
| Education Mandate        | Education Metric  |  Interesting Insight
|---------------|:-------------:|
| Sexual decision making and self-discipline | % students intoxicated   |  Suggests that education on sexual decision making may not be effective, since those states where most students were intoxicated during their last sexual encounter do mandate this type of education. |
| Sex Ed Marriage | % students with one or more partners  | The three states in which the most students have had four or more sexual partners also mandate sex ed that emphasises waiting for marriage to have sex. |"

cat(tabl) # output the table in a format good for HTML/PDF/docx conversion
```

```{r table2, echo=FALSE, message=FALSE, warnings=FALSE, results='asis'}
##Corresponds with lauren_blog3

tabl <- "
| Education Mandate        | Practice/Behavior  |  Interesting Insight |
|---------------|:-------------:|
| Sex Ed Mandated | Provided Educators with Strategies   | 
There are 8 states in which sex ed is mandated but in which fewer than 70% of schools provide teachers strategies for teaching sex ed. In these states, teachers have a large amount of discretion. (However, it is unclear if this disparity between mandate and policy has an effect on student health. All of these 8 states have an STD index of 0.45 or lower, scoring better than about half of all states. In fact, one of the states, Vermont, has the lowest STD index of any state. By another metric, births per 1,000 girls, this result is less definitive: the states fall over a wide range, from 27.2 (Kentucky) to 8.8 (Vermont).) |"

cat(tabl) # output the table in a format good for HTML/PDF/docx conversion
```

```{r table2, echo=FALSE, message=FALSE, warnings=FALSE, results='asis'}
##

tabl <- "
| Education Mandate        | Resource Offered by High Schools  |  Interesting Insight |
|---------------|:-------------:|
| HIV Ed Mandated | Increased Student Knowledge on HIV Prevention  | 
There are 8 states in which sex ed is mandated but in which fewer than 70% of schools provide teachers strategies for teaching sex ed. In these states, teachers have a large amount of discretion. (However, it is unclear if this disparity between mandate and policy has an effect on student health. All of these 8 states have an STD index of 0.45 or lower, scoring better than about half of all states. In fact, one of the states, Vermont, has the lowest STD index of any state. By another metric, births per 1,000 girls, this result is less definitive: the states fall over a wide range, from 27.2 (Kentucky) to 8.8 (Vermont).) |
| Sex Ed Orientation | Increased Student Knowledge on Sexuality | Without a mandate (coded as 0) and with a mandate (coded as 1), the percentage of teachers that tried to increase knowledge on human sexuality is highly concentrated from 70-90%. Due to the high variance in the percentage among states without a mandate, the average percentage is lower than in states with a mandate. |"

cat(tabl) # output the table in a format good for HTML/PDF/docx conversion
```
```{r table2, echo=FALSE, message=FALSE, warnings=FALSE, results='asis'}
##Corresponds with school_edu_scatter

tabl <- "
| Education Mandate        | Resource Offered by High Schools  |  Interesting Insight |
|---------------|:-------------:|
| Increased Student Knowledge on STD Prevention | STD Index  | 
This display provides some evidence that teachers’ efforts to improve students' knowledge on STD prevention improves their ability to protect themselves from STDs. |
| Increased Student knowledge on HIV Prevention | HIV Per 100K | d Student knowledge on HIV Prevention, HIV Per 100K |
Similarly, this display tells an optimistic story about teachers’ ability to help students protect themselves from HIV. 
 |"

cat(tabl) # output the table in a format good for HTML/PDF/docx conversion
```
