---
title: "Implications of Sex Ed on Teen Sexual Health by State"
author: "Aditi Nayak, Lauren Pelosi, Catherine Sarosi"
date: "11/19/2020"
output:
  rmdformats::readthedown:
    thumbnails: false
    highlight: NULL
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align="center")
library(tidyverse)
library(shiny)
```

# Introduction

<div style="width:100%;height:0;padding-bottom:56%;position:relative;"><iframe src="https://giphy.com/embed/3o7aTDP5aDFogC5KmY" width="100%" height="100%" style="position:absolute" frameBorder="0" class="giphy-embed" allowFullScreen></iframe></div><p><a href="https://giphy.com/gifs/filmeditor-movie-mean-girls-3o7aTDP5aDFogC5KmY">via GIPHY</a></p>

Sexual health is still a taboo topic across the United States. The openness in conversations about this topic vary by state, community, family, and even individual. As a result, students across the nation have vastly different sexual education experiences: some like the above scene in Mean Girls and others more comprehensive. 

This inconsistency and inequity in sexual education requirements across the nation is not only awkward but can also be consequential for teens. Like an accounting course prepares students for future finances and English classes helps students communicate better, sexual education helps students navigate their sexuality and safely engage in sexual activity. Without sexual education, students are less prepared to manage their sexual and reproductive health and behavior, which can lead to unwanted pregnancy and sexually transmitted diseases (STD).

Given how consequential sexual education can be to teenagers, we investigated how sexual education impacts certain health outcomes. The general effectiveness of sexual education is a broad topic, so we narrowed in on the following questions:

## Research Questions
(1) How do statewide mandates and what high schools teach compare to student health outcomes?
(2) Do student behaviors determine health outcomes?
(3) What groupings form based on health outcomes?

## Data

# How do statewide mandates and what high schools teach compare to student health outcomes?

## Are stricter mandates effective in improving student health outcomes?
## How do statewide mandates and that state’s high schools’ sex ed programs compare?
## Are school policies and teachers’ efforts effective in improving student health outcomes?
## Do school policies and teachers’ efforts impact student behaviors?

# Do student behaviors determine health outcomes?

# What groupings form based on health outcomes?

## Embedding bar plot 

<iframe height="600" width="100%" frameborder="no" title="Increase in Global Temperature" src="https://anayak23.shinyapps.io/Blog_library_Fauci_lauren/ "> </iframe>

# Conclusions

# References

